'use client'

import dynamic from 'next/dynamic'
import { useEffect, useMemo, useState } from 'react'
import { Bell, Camera, Check, ChevronLeft, Clock3, Flag, Home, Languages, MapPin, Plus, Search, ShieldCheck, Star, UserRound } from 'lucide-react'
import type { User } from '@supabase/supabase-js'
import { createClient } from '@/lib/supabase'
import AuthSheet from '@/components/AuthSheet'

const NearbyMap=dynamic(()=>import('@/components/NearbyMap'),{ssr:false})

type Tab='home'|'ask'|'alerts'|'profile'
type Place={id?:string;name:string;address:string;lat:number;lng:number}
type Answer={id:string;question_id:string;user_id:string|null;body:string;photo_url:string|null;created_at:string;pending_until?:string|null;payout_status?:string|null;verified_photo?:boolean|null;tip_cents?:number|null}
type Question={id:string;user_id:string|null;body:string;place:string|null;lat:number|null;lng:number|null;created_at:string;reward_cents:number;fee_cents?:number;status:string;expires_at?:string|null;claim_user_id?:string|null;claim_expires_at?:string|null;photo_required?:boolean;question_photo_url?:string|null;answers?:Answer[]}

const feeFor=(reward:number)=>reward===100?29:reward===200?49:reward===300?59:reward===500?79:0
const claimMinutes=(limit:number)=>limit===5?2:limit===10?4:5
const money=(c=0)=>`$${(c/100).toFixed(2)}`
const badAnswer=(s:string)=>{const x=s.trim().toLowerCase();return x.length<8||['idk','i dont know','i don\'t know','no idea','maybe','not sure'].includes(x)}
const timeLeft=(iso?:string|null)=>{if(!iso)return '';const ms=new Date(iso).getTime()-Date.now();if(ms<=0)return 'Expired';const m=Math.ceil(ms/60000);return `${m} min left`}

export default function HomePage(){
 const supabase=useMemo(()=>createClient(),[])
 const [user,setUser]=useState<User|null>(null); const [authOpen,setAuthOpen]=useState(false); const [tab,setTab]=useState<Tab>('home')
 const [questions,setQuestions]=useState<Question[]>([]); const [coords,setCoords]=useState<{lat:number,lng:number}|null>(null); const [selected,setSelected]=useState<Question|null>(null)
 const [askBody,setAskBody]=useState(''); const [reward,setReward]=useState(200); const [limit,setLimit]=useState(15); const [place,setPlace]=useState<Place|null>(null); const [placeOpen,setPlaceOpen]=useState(false); const [photoRequired,setPhotoRequired]=useState(false)
 const [search,setSearch]=useState(''); const [placeResults,setPlaceResults]=useState<Place[]>([]); const [answer,setAnswer]=useState(''); const [answerPhoto,setAnswerPhoto]=useState<File|null>(null); const [answerPhotoPreview,setAnswerPhotoPreview]=useState(''); const [notice,setNotice]=useState('')
 const [now,setNow]=useState(Date.now())
 useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),15000);return()=>clearInterval(t)},[])
 useEffect(()=>{if(!supabase)return;supabase.auth.getUser().then(({data})=>setUser(data.user));const {data:s}=supabase.auth.onAuthStateChange((_e,ss)=>setUser(ss?.user||null));load();const ch=supabase.channel('nearby-live').on('postgres_changes',{event:'*',schema:'public',table:'questions'},()=>load()).on('postgres_changes',{event:'*',schema:'public',table:'answers'},()=>load()).subscribe();return()=>{s.subscription.unsubscribe();supabase.removeChannel(ch)}},[supabase])
 async function load(){if(!supabase)return;const {data:q}=await supabase.from('questions').select('*').order('created_at',{ascending:false}).limit(100);if(!q)return;const ids=q.map((x:any)=>x.id);const {data:a}=ids.length?await supabase.from('answers').select('*').in('question_id',ids):{data:[] as any[]};const grouped:Record<string,Answer[]>={};for(const x of (a||[]) as any[]){(grouped[x.question_id]??=[]).push(x)}setQuestions((q as any[]).map(x=>({...x,answers:grouped[x.id]||[]})))}
 function requireUser(action:()=>void){if(user)action();else setAuthOpen(true)}
 function useLocation(){navigator.geolocation?.getCurrentPosition(async p=>{const c={lat:p.coords.latitude,lng:p.coords.longitude};setCoords(c);const r=await fetch(`/api/places/reverse?lat=${c.lat}&lng=${c.lng}`);if(r.ok){const x=await r.json();setPlace({name:x.name||'Current location',address:x.address||'',lat:c.lat,lng:c.lng})}},()=>setNotice('Location permission was not granted.'),{enableHighAccuracy:true,timeout:10000})}
 async function searchPlaces(q:string){setSearch(q);if(q.trim().length<2){setPlaceResults([]);return}const url=`/api/places/search?q=${encodeURIComponent(q)}${coords?`&lat=${coords.lat}&lng=${coords.lng}`:''}`;const r=await fetch(url);if(r.ok)setPlaceResults(await r.json())}
 async function postQuestion(){requireUser(async()=>{if(!supabase||!user)return;if(!askBody.trim()||!place)return setNotice('Add a question and choose a place.');const expires=new Date(Date.now()+limit*60000).toISOString();const {error}=await supabase.from('questions').insert({user_id:user.id,body:askBody.trim(),place:`${place.name}${place.address?` · ${place.address}`:''}`,lat:place.lat,lng:place.lng,reward_cents:reward,fee_cents:feeFor(reward),status:'open',expires_at:expires,photo_required:photoRequired});if(error)return setNotice(error.message);setAskBody('');setPlace(null);setReward(200);setLimit(15);setPhotoRequired(false);setTab('home');setNotice('Question posted. Reward is virtual during family testing.');load()})}
 async function claim(q:Question){requireUser(async()=>{if(!supabase||!user)return;if(q.user_id===user.id)return setNotice('You cannot claim your own question.');const mins=claimMinutes(Math.max(5,Math.round((new Date(q.expires_at||Date.now()).getTime()-new Date(q.created_at).getTime())/60000)));const {data,error}=await supabase.rpc('claim_question_family',{p_question_id:q.id,p_claim_minutes:mins});if(error)return setNotice(error.message);if(!data)return setNotice('Someone else claimed it first.');setNotice(`You have ${mins} minutes to check it.`);load()})}
 async function uploadPhoto(qid:string,file:File){if(!supabase||!user)return null;const ext=file.name.split('.').pop()||'jpg';const path=`answers/${user.id}/${qid}-${Date.now()}.${ext}`;const {error}=await supabase.storage.from('nearby-photos').upload(path,file,{upsert:false});if(error){setNotice(error.message);return null}const {data}=supabase.storage.from('nearby-photos').getPublicUrl(path);return data.publicUrl}
 async function submitAnswer(q:Question){requireUser(async()=>{if(!supabase||!user)return;if(q.claim_user_id!==user.id)return setNotice('Claim this question first.');if(badAnswer(answer))return setNotice('Please give a useful, specific answer. “IDK” or very short answers are blocked.');if(q.photo_required&&!answerPhoto)return setNotice('This question requires a photo.');let photoUrl:string|null=null;if(answerPhoto)photoUrl=await uploadPhoto(q.id,answerPhoto);const pending=new Date(Date.now()+10*60000).toISOString();const {error}=await supabase.from('answers').insert({question_id:q.id,user_id:user.id,body:answer.trim(),photo_url:photoUrl,verified_photo:!!answerPhoto,pending_until:pending,payout_status:'pending'});if(error)return setNotice(error.message);await supabase.from('questions').update({status:'answered'}).eq('id',q.id);setAnswer('');setAnswerPhoto(null);setAnswerPhotoPreview('');setNotice('Answer submitted. Virtual reward is pending for 10 minutes.');load()})}
 async function looksGood(q:Question,a:Answer){if(!supabase||!user||q.user_id!==user.id)return;await supabase.from('answers').update({payout_status:'released',pending_until:new Date().toISOString()}).eq('id',a.id);await supabase.from('questions').update({status:'completed'}).eq('id',q.id);setNotice(`${money(q.reward_cents)} virtual reward released.`);load()}
 async function report(q:Question,a:Answer){if(!supabase||!user||q.user_id!==user.id)return;const reason=prompt('Choose a reason:\n1 Answer does not address my question\n2 Required photo is missing\n3 Wrong location or item\n4 Spam or fake answer');if(!reason)return;await supabase.from('disputes').insert({question_id:q.id,answer_id:a.id,reporter_id:user.id,reason});await supabase.from('answers').update({payout_status:'disputed'}).eq('id',a.id);setNotice('Reported for family-test review.');load()}
 async function signOut(){if(supabase)await supabase.auth.signOut()}
 const activeQuestions=questions.filter(q=>q.status!=='cancelled'&&timeLeft(q.expires_at)!=='Expired')
 return <main className="appShell">
  <AuthSheet open={authOpen} onClose={()=>setAuthOpen(false)}/>
  {notice&&<button className="toast" onClick={()=>setNotice('')}>{notice}</button>}
  <header className="header"><div className="brandIcon"><span>Near<br/>By</span><i/></div><div className="brandText">Near By</div><button className="headerBtn"><Bell size={21}/></button><button className="avatar" onClick={()=>setTab('profile')}>{user?.email?.[0]?.toUpperCase()||'N'}</button></header>
  {tab==='home'&&<>
   <section className="mapWrap">{coords?<NearbyMap lat={coords.lat} lng={coords.lng} pins={activeQuestions}/>:<div className="mapFake"><div className="mapGrid"/><button className="locationPill" onClick={useLocation}><MapPin size={16}/> Use my location</button></div>}</section>
   <section className="section"><div className="sectionTitle"><h2>Questions Nearby</h2><button className="circleBtn"><Search size={20}/></button></div><div className="filters"><button className="active">All</button><button>With reward</button><button>Following</button></div>
   <div className="cards">{activeQuestions.length===0?<div className="empty"><MapPin/><b>No live questions yet.</b><span>Post one from the Ask tab to start the family test.</span></div>:activeQuestions.map(q=><article className="qCard" key={q.id} onClick={()=>setSelected(q)}><div className="qTop"><div><span className="place">{q.place||'Nearby'}</span><h3>{q.body}</h3></div><b className="reward">{money(q.reward_cents)}</b></div><div className="qMeta"><span><Clock3 size={14}/>{timeLeft(q.expires_at)}</span><span>{q.status==='claimed'?'Helper checking':q.status==='answered'?'Answer received':q.status==='completed'?'Completed':'Open'}</span></div></article>)}</div></section>
  </>}
  {tab==='ask'&&<section className="page"><div className="pageHead"><h1>Ask a Question</h1></div><label>What do you want to know?</label><textarea className="textarea" maxLength={200} value={askBody} onChange={e=>setAskBody(e.target.value)} placeholder="Does Walmart in Duluth have cup noodles?"/><div className="counter">{askBody.length}/200</div><label>Location</label><button className="placeBox" onClick={()=>setPlaceOpen(true)}><div><b>{place?.name||'Choose a place'}</b><span>{place?.address||'Search for a store or venue'}</span></div><MapPin/></button><label>Set a reward</label><p className="hint">100% of the reward goes to the person who helps you.</p><div className="rewardGrid">{[100,200,300,500].map(v=><button key={v} className={reward===v?'active':''} onClick={()=>setReward(v)}>{money(v)}</button>)}</div><div className="priceBox"><div><span>Reward</span><b>{money(reward)}</b></div><div><span>Near By fee</span><b>{money(feeFor(reward))}</b></div><div className="total"><span>Total</span><b>{money(reward+feeFor(reward))}</b></div><small>Family test: no real money moves yet.</small></div><label>Time limit</label><select className="input" value={limit} onChange={e=>setLimit(Number(e.target.value))}>{Array.from({length:12},(_,i)=>(i+1)*5).map(v=><option key={v} value={v}>{v} minutes{v===5?' · Quick':''}</option>)}</select>{limit===5&&<div className="quickNote">⚡ 5-minute questions are best for someone already at the location. A helper gets a 2-minute claim window.</div>}<label className="checkRow"><input type="checkbox" checked={photoRequired} onChange={e=>setPhotoRequired(e.target.checked)}/><span><b>Require a photo</b><small>Good for stock, lines, shelves, parking and other visual checks.</small></span></label><button className="primary" onClick={postQuestion}>Post Question · {money(reward+feeFor(reward))} virtual</button></section>}
  {tab==='alerts'&&<section className="page"><div className="pageHead"><h1>Alerts</h1></div><div className="empty"><Bell/><b>Family-test alerts</b><span>Realtime question and answer changes appear automatically. Push notifications come later.</span></div></section>}
  {tab==='profile'&&<section className="page"><div className="profileHero"><div className="profileAvatar">{user?.email?.[0]?.toUpperCase()||'N'}</div><h1>{user?'Your Profile':'Guest'}</h1><p>{user?.email||'Sign in only when you need to ask or answer.'}</p><div className="stars"><Star fill="currentColor"/>4.9 <span>(family test)</span></div></div><div className="stats"><div><b>{questions.filter(q=>q.user_id===user?.id).length}</b><span>Questions</span></div><div><b>{questions.flatMap(q=>q.answers||[]).filter(a=>a.user_id===user?.id).length}</b><span>Answers</span></div><div><b>$0</b><span>Virtual earned</span></div></div><div className="settingsCard"><div><Languages/>Preferred language <b>English</b></div><div><ShieldCheck/>Exact location <b>Private</b></div></div>{user?<button className="secondary" onClick={signOut}>Sign out</button>:<button className="primary" onClick={()=>setAuthOpen(true)}>Sign in / Create account</button>}</section>}
  <nav className="bottomNav"><button className={tab==='home'?'active':''} onClick={()=>setTab('home')}><Home/><span>Home</span></button><button className={tab==='ask'?'active':''} onClick={()=>setTab('ask')}><Plus/><span>Ask</span></button><button className={tab==='alerts'?'active':''} onClick={()=>setTab('alerts')}><Bell/><span>Alerts</span></button><button className={tab==='profile'?'active':''} onClick={()=>setTab('profile')}><UserRound/><span>Profile</span></button></nav>
  {placeOpen&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setPlaceOpen(false)}}><section className="sheet"><div className="sheetHandle"/><div className="row"><button className="iconBtn" onClick={()=>setPlaceOpen(false)}><ChevronLeft/></button><h2>Choose a place</h2></div><button className="secondary" onClick={useLocation}><MapPin/> Use my current location</button><div className="searchBox"><Search/><input value={search} onChange={e=>searchPlaces(e.target.value)} placeholder="Walmart Duluth, Target Alpharetta…"/></div><div className="placeResults">{placeResults.map(p=><button key={p.id} onClick={()=>{setPlace(p);setPlaceOpen(false)}}><MapPin/><div><b>{p.name}</b><span>{p.address}</span></div></button>)}</div><p className="legalMini">Your exact location is used for nearby search only and is not shown to other users.</p></section></div>}
  {selected&&<div className="overlay"><section className="sheet detail"><div className="sheetHandle"/><div className="row spread"><button className="iconBtn" onClick={()=>setSelected(null)}><ChevronLeft/></button><span className="timer">{timeLeft(selected.expires_at)}</span></div><span className="place">{selected.place}</span><h2>{selected.body}</h2><div className="detailReward"><span>Reward</span><b>{money(selected.reward_cents)}</b></div>{selected.status==='open'&&selected.user_id!==user?.id&&<button className="primary" onClick={()=>claim(selected)}>I’ll check · Earn {money(selected.reward_cents)}</button>}{selected.claim_user_id===user?.id&&selected.status==='claimed'&&<div className="answerForm"><div className="claimBanner">Claimed by you · submit before {new Date(selected.claim_expires_at||'').toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})} + 1 min grace</div><textarea className="textarea" value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Be specific. Example: Yes — 6 left on aisle 12."/><label className="cameraBtn"><Camera/> Take a photo now<input hidden type="file" accept="image/*" capture="environment" onChange={e=>{const f=e.target.files?.[0]||null;setAnswerPhoto(f);if(f)setAnswerPhotoPreview(URL.createObjectURL(f))}}/></label>{answerPhotoPreview&&<img className="photoPreview" src={answerPhotoPreview} alt="answer preview"/>}<p className="hint">For family testing, a fresh camera photo is marked as verified. Production verification will add stronger anti-fake checks.</p><button className="primary" onClick={()=>submitAnswer(selected)}>Submit Answer</button></div>}{(selected.answers||[]).map(a=><div className="answerCard" key={a.id}><div className="row spread"><b>Answer received</b>{a.verified_photo&&<span className="verified"><Check/> Verified photo</span>}</div><p>{a.body}</p>{a.photo_url&&<img src={a.photo_url} alt="answer"/>}{selected.user_id===user?.id&&<><div className="pending"><b>{money(selected.reward_cents)}</b> virtual reward {a.payout_status==='released'?'released':a.payout_status==='disputed'?'disputed':`pending · auto-release in about 10 min`}</div>{a.payout_status==='pending'&&<div className="two"><button className="primary" onClick={()=>looksGood(selected,a)}>Looks good</button><button className="secondary danger" onClick={()=>report(selected,a)}><Flag/>Report a problem</button></div>}</>}</div>)}</section></div>}
 </main>
}
